"""docx/md import cycle. The docx fixture is generated by pandoc itself
(md -> docx, embedding a real PNG), then run through the import endpoint —
covering conversion, media extraction, URI rewriting, and toctree
registration end-to-end without hand-crafted binary fixtures."""

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.deps import get_store
from app.main import app
from rstkit.store import LocalGitStore

_PNG_1PX = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4"
    "890000000a49444154789c6360000002000100ffff03000006000557bfabd400"
    "00000049454e44ae426082"
)

INDEX = (
    "Docs\n"
    "====\n"
    "\n"
    ".. toctree::\n"
    "\n"
    "   existing\n"
)

MD_SOURCE = """# Импортированный документ

Первый абзац с **жирным** текстом и списком:

- пункт один
- пункт два

| Колонка А | Колонка Б |
|-----------|-----------|
| 1         | два       |

![Схема](diagram.png)
"""


@pytest.fixture()
def workspace(tmp_path):
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "index.rst").write_text(INDEX, encoding="utf-8")
    (docs / "existing.rst").write_text("E\n=\n", encoding="utf-8")
    app.dependency_overrides[get_store] = lambda: LocalGitStore(docs)
    client = TestClient(app)
    yield docs, client
    app.dependency_overrides.clear()


def _make_docx(tmp_path: Path) -> bytes:
    import pypandoc

    md = tmp_path / "src.md"
    md.write_text(MD_SOURCE, encoding="utf-8")
    (tmp_path / "diagram.png").write_bytes(_PNG_1PX)
    out = tmp_path / "src.docx"
    pypandoc.convert_file(
        str(md), to="docx", format="markdown", outputfile=str(out),
        extra_args=[f"--resource-path={tmp_path}"],
    )
    return out.read_bytes()


def test_import_markdown(workspace, tmp_path):
    docs, client = workspace
    r = client.post(
        "/api/import",
        data={"path": "imported.rst", "toctree_index": "index.rst"},
        files={"file": ("notes.md", MD_SOURCE.encode("utf-8"), "text/markdown")},
    )
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["toctree_updated"] is True

    raw = (docs / "imported.rst").read_bytes()
    text = raw.decode("utf-8")
    assert "Импортированный документ" in text
    assert "**жирным**" in text
    assert "пункт один" in text
    assert "\r\n" in text  # corpus EOL convention
    assert "   imported" in (docs / "index.rst").read_text(encoding="utf-8")

    # imported page opens through the normal doc pipeline
    d = client.get("/api/doc/imported.rst")
    assert d.status_code == 200
    assert any(n["type"] == "heading" for n in d.json()["doc"]["nodes"])


def test_import_docx_with_embedded_image(workspace, tmp_path):
    docs, client = workspace
    docx = _make_docx(tmp_path)

    r = client.post(
        "/api/import",
        data={"path": "word/report.rst"},
        files={
            "file": (
                "report.docx",
                docx,
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            )
        },
    )
    assert r.status_code == 200, r.text

    text = (docs / "word" / "report.rst").read_bytes().decode("utf-8")
    assert "Импортированный документ" in text
    assert "**жирным**" in text

    # the embedded PNG landed in media/ next to the doc, and the rst points there
    media = list((docs / "word" / "media").glob("*.png"))
    assert media, "extracted image missing"
    assert f"media/{media[0].name}" in text
    assert media[0].read_bytes()[:8] == _PNG_1PX[:8]

    # and the asset resolves through the normal asset endpoint
    a = client.get("/api/asset", params={"doc": "word/report.rst", "uri": f"media/{media[0].name}"})
    assert a.status_code == 200


def test_import_rejects_legacy_doc(workspace):
    _, client = workspace
    r = client.post(
        "/api/import",
        data={"path": "old.rst"},
        files={"file": ("old.doc", b"\xd0\xcf\x11\xe0junk", "application/msword")},
    )
    assert r.status_code == 422
    assert ".docx" in r.json()["detail"]


def test_import_rejects_existing_target(workspace):
    _, client = workspace
    r = client.post(
        "/api/import",
        data={"path": "existing.rst"},
        files={"file": ("n.md", b"# X", "text/markdown")},
    )
    assert r.status_code == 409


def test_imported_file_saves_round_trip_clean(workspace):
    """Phase 8 AC: converted doc saves round-trip-clean via the save API."""
    docs, client = workspace
    r = client.post(
        "/api/import",
        data={"path": "clean.rst"},
        files={"file": ("n.md", MD_SOURCE.encode("utf-8"), "text/markdown")},
    )
    assert r.status_code == 200

    before = (docs / "clean.rst").read_bytes()
    payload = client.get("/api/doc/clean.rst").json()
    blocks = [{"op": "raw", "raw": n["raw_source"]} for n in payload["doc"]["nodes"]]
    r = client.put(
        "/api/doc/clean.rst",
        json={"base_mtime_ns": payload["mtime_ns"], "blocks": blocks},
    )
    assert r.status_code == 200, r.text
    assert (docs / "clean.rst").read_bytes() == before